title = "Louise Grandjonc, Python/SQL developer but also a human"
baseURL = "http://www.louisemeta.com/"
tags = ["developer blog", "postgreSQL", "python"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-116410295-1"
publishDir = "docs"

[Params]
    tagline = "LouiseMeta"
    author = "Louise Grandjonc"
    description = "Python/Django/SQL developer, PostgreSQL enthousiast"
    logoBig = "/images/Owls_dance_04.png"
    logoSmall = "/images/Owls_dance_04.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/Owls_dance_04.png"
    twitter = "louisemeta"
    linkedin = "louise-grandjonc-81502b80"
    github = "louiseGrandjonc"
    facebook = ""
    email = ""
    googleTagManger = ""
    highlightJS = true
    copyright = false
    credit = false
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2
[[menu.main]]
    name = "Talks"
    url  = "/talks/"
    weight = 3
[[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 4
